<?php
function fred_page_alter(&$page) {
  drupal_set_message('in hook_page_alter');
  $page['content']['bartik.content']['content']['#markup'] = 'Hello, content!!!';
  //Render the library as laid out in wfm_store_select.libraries.yml
  //Maybe check if we only want to do it on page 'store-list2'
  //$page['#attached']['library'][] = 'wfm_store_select/store_select';
}

function fred_page_build(&$page) {
  drupal_set_message('in hook page build');
  $path = drupal_get_path('module', 'wfm_store_select');
  //$page['#attached']['js'][$path . 'js/wfm_store_select.js'] = array('every_page' => TRUE);
}

