<?php

/**
 * @file
 * Contains my_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_entity module.
    case 'help.page.my_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Learning D8 Entity API') . '</p>';
      return $output;

    default:
  }
}
